services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://gambler:ilovegambling@postgres:5433/casino?sslmode=disable
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: gambler
      POSTGRES_PASSWORD: ilovegambling
      POSTGRES_DB: casino
    expose:
      - "5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

  frontend:
    build: ./frontend
    expose:
      - "81:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  pgdata: